from sqlalchemy.orm import Session
from typing import Optional
from app.models import user as models_user  # Alias to avoid confusion
from app.schemas import user as schemas_user
from app.core.security import get_password_hash


def get_user_by_email(db: Session, email: str) -> Optional[models_user.User]:
    return db.query(models_user.User).filter(models_user.User.email == email).first()


def create_user(db: Session, user: schemas_user.UserCreate) -> models_user.User:
    hashed_password = get_password_hash(user.password)
    # tenant_id is generated by default in the model now.
    db_user = models_user.User(
        email=user.email,
        hashed_password=hashed_password,
        full_name=user.full_name,
        # tenant_id is handled by default in the model
    )
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return db_user
